---
title: "A new heteroskedasticity-robust test for explosive bubbles"
subtitle: "A test for explosive bubbles that is robust to heteroskedasticity in the innovations."
description: "Harvey, D. I., Leybourne, S. J., Taylor, A. M. R. and **Zu, Y.** (2024). *Journal of Time Series Analysis*."
date: 2024-06-01
categories: ["Bubble testing", "Time-varying volatility"]
---

## Abstract

We propose a new class of modified regression‐based tests for detecting asset price bubbles designed to be robust to the presence of general forms of both conditional and unconditional heteroskedasticity in the price series. This modification, based on the approach developed in Beare (2018) in the context of conventional unit root testing, is achieved by purging the impact of unconditional heteroskedasticity from the data using a kernel estimate of volatility before the application of the bubble detection methods proposed in Phillips, Shi and Yu (2015) (PSY). The modified statistic is shown to achieve the same limiting null distribution as the corresponding (heteroskedasticity‐uncorrected) statistic from PSY would obtain under homoskedasticity, such that the usual critical values provided in PSY may still be used. Versions of the test based on regressions including either no intercept or a (redundant) intercept are considered. Representations for asymptotic local power against a single bubble model are also derived. Monte Carlo simulation results highlight that neither one of these tests dominates the other across different bubble locations and magnitudes, and across different models of time‐varying volatility. Accordingly, we also propose a test based on a union of rejections between the with‐ and without‐intercept variants of the modified PSY test. The union procedure is shown to perform almost as well as the better of the constituent tests for a given DGP, and also performs very well compared to existing heteroskedasticity‐robust tests across a large range of simulation DGPs.

## Links

- [Journal](https://doi.org/10.1111/jtsa.12784)

## BibTeX

```bibtex
@article{Harvey_2024, title={A new heteroskedasticity‐robust test for explosive bubbles}, volume={46}, ISSN={1467-9892}, url={http://dx.doi.org/10.1111/jtsa.12784}, DOI={10.1111/jtsa.12784}, number={5}, journal={Journal of Time Series Analysis}, publisher={Wiley}, author={Harvey, David I. and Leybourne, Stephen J. and Taylor, A. M. Robert and Zu, Yang}, year={2024}, month=Oct, pages={846–866} }
```
